services:


  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    command:
      - '--config=/litellm_config.yaml'
      - '--detailed_debug'
    ports:
      - '127.0.0.1:4000:4000'
    environment:
      - LITELLM_MASTER_KEY=dummy
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./litellm_config.yaml:/litellm_config.yaml

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    env_file:
      - .env
    volumes:
      - open-webui:/app/backend/data
      - ./backend/logs:/app/backend/logs
      - ./bioinformatics_mcp:/app/bioinformatics_mcp
      # Mount backend code for development
      - ./backend:/app/backend
      # Shared file storage for bioinformatics data
      - shared-files:/app/shared_files
      - ./shared_files:/app/shared_files_host
    depends_on:
      - litellm
    ports:
      - "3000:8080"
    environment:
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_URL=http://localhost:3000'
      - 'ENABLE_OPENAI_API=true'
      - 'OPENAI_API_BASE_URLS=http://litellm:4000/v1'
      - 'OPENAI_API_KEYS=dummy'
      - 'DEFAULT_MODELS=claude-3-5-sonnet'
      # File sharing configuration
      - 'SHARED_FILES_PATH=/app/shared_files'
      - 'HOST_SHARED_FILES_PATH=/app/shared_files_host'
      - 'MAX_FILE_SIZE_MB=500'
      - 'ALLOWED_EXTENSIONS=fastq,fq,fa,fasta,sam,bam,vcf,gff,gtf,bed,txt,csv,tsv,json,xml,png,jpg,jpeg,pdf'
      - 'ENABLE_FILE_SHARING=true'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  # omics-runner:
  #   build:
  #     context: ./backend/omics_runner
  #     dockerfile: .Dockerfile
  #   container_name: omics-runner
  #   privileged: true
  #   cap_add:
  #     - SYS_ADMIN
  #   devices:
  #     - /dev/fuse:/dev/fuse
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./backend/omics_runner:/app
  #     # Shared file storage - same mount as Open WebUI
  #     - user-files:/user-files
  #     - ./user-files:/user-files_host
  #   environment:
  #     # File sharing configuration
  #     - 'SHARED_FILES_PATH=/user-files'
  #     - 'HOST_SHARED_FILES_PATH=/user-files_host'
  #     - 'MAX_FILE_SIZE_MB=500'
  #     - 'ALLOWED_EXTENSIONS=fastq,fq,fa,fasta,sam,bam,vcf,gff,gtf,bed,txt,csv,tsv,json,xml,png,jpg,jpeg,pdf'
  #     # Azure Storage configuration
  #     - 'AZURE_STORAGE_ENDPOINT=https://entropicstorage.blob.core.windows.net/'
  #     - 'AZURE_STORAGE_CONTAINER_NAME=user-files'
  #     - 'AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}'
  #   restart: unless-stopped
  #   depends_on:
  #     - open-webui

volumes:
  ollama: {}
  open-webui: {}
  shared-files: {}
  user-files: {}
