 name: bioinformatics-mcp
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.12
  - mcp>=1.7.1
  - snakemake>=9.3.3
  - conda-build>=25.4.2
  - openai>=1.77.0
  - pip
  - pytest>=8.3.5
  - samtools
  - bcftools
  - picard
  - pip:
    - smolagents==1.14.0
    - mcpo==0.0.14 