from typing import Optional
import subprocess
from bioinformatics_mcp.tool_decorator import collect_tool
from bioinformatics_mcp.core.snake_wrapper import run_snake_wrapper


def run_bismark2bedGraph(
    *,
    cpg_context_file: str,
    chg_context_file: Optional[str] = None,
    chh_context_file: Optional[str] = None,
    extra: Optional[str] = None,
    bedGraph: str,
    cov: Optional[str] = None,
     
) -> subprocess.CompletedProcess:
    """
    Generate bedGraph and coverage files from positional methylation files created by bismark_methylation_extractor.

    Args:
        cpg_context_file: File generated by bismark_methylation_extractor, e.g. CpG_context*.txt.gz
        chg_context_file (optional): File for CHG context, e.g. CHG_context*.txt.gz
        chh_context_file (optional): File for CHH context, e.g. CHH_context*.txt.gz
        extra (optional): Additional args, e.g. '--CX', '--ample_memory', ' --buffer_size 10G', etc.
        bedGraph: Output Bismark methylation level track, *.bedGraph.gz (0-based start, 1-based end coordinates)
        cov (optional): Output Bismark coverage file *.bismark.cov.gz
           
    Returns:
        CompletedProcess instance containing information about the completed Snakemake process
    """
    return run_snake_wrapper(
        wrapper="file:bioinformatics_mcp/bismark/bismark2bedGraph",
        inputs={
            "cpg_context_file": cpg_context_file,
            "chg_context_file": chg_context_file,
            "chh_context_file": chh_context_file,
        },
        params={"extra": extra} if extra else {},
        outputs={"bedGraph": bedGraph, "cov": cov},
         
    )


@collect_tool()
def bismark2bedGraph(
    *,
    cpg_context_file: str,
    chg_context_file: Optional[str] = None,
    chh_context_file: Optional[str] = None,
    extra: Optional[str] = None,
    bedGraph: str,
    cov: Optional[str] = None,
     
) -> subprocess.CompletedProcess:
    """
    Generate bedGraph and coverage files from positional methylation files created by bismark_methylation_extractor.

    Args:
        cpg_context_file: File generated by bismark_methylation_extractor, e.g. CpG_context*.txt.gz
        chg_context_file (optional): File for CHG context, e.g. CHG_context*.txt.gz
        chh_context_file (optional): File for CHH context, e.g. CHH_context*.txt.gz
        extra (optional): Additional args, e.g. '--CX', '--ample_memory', ' --buffer_size 10G', etc.
        bedGraph: Output Bismark methylation level track, *.bedGraph.gz (0-based start, 1-based end coordinates)
        cov (optional): Output Bismark coverage file *.bismark.cov.gz
           
    Returns:
        CompletedProcess instance containing information about the completed Snakemake process
    """
    return run_bismark2bedGraph(
        cpg_context_file=cpg_context_file,
        chg_context_file=chg_context_file,
        chh_context_file=chh_context_file,
        extra=extra,
        bedGraph=bedGraph,
        cov=cov,
         
    )
