from typing import Optional
import subprocess
from tools.tool_decorator import collect_tool
from core.snake_wrapper import run_snake_wrapper


def run_plotheatmap(
    *,
    matrix_file: str,
    heatmap_img: str,
    regions: Optional[str] = None,
    heatmap_matrix: Optional[str] = None,
     
) -> subprocess.CompletedProcess:
    """
    `deepTools plotHeatmap` creates a heatmap for scores associated with genomic regions.

    Args:
        matrix_file: Path to the gzipped matrix file generated by `deepTools computeMatrix` (.gz).
        heatmap_img: Output path for the plot image (.png, .eps, .pdf, or .svg). This is required.
        regions (optional): Output path for the BED file with sorted regions (.bed).
        heatmap_matrix (optional): Output path for the tab-separated matrix file (.tab).
  
    Returns:
        CompletedProcess instance containing information about the completed Snakemake process.
    """
    return run_snake_wrapper(
        wrapper="file:tools/deeptools/plotheatmap",
        inputs={"matrix_file": matrix_file},
        outputs={
            "heatmap_img": heatmap_img,
            **({"regions": regions} if regions else {}),
            **({"heatmap_matrix": heatmap_matrix} if heatmap_matrix else {}),
        },
         
    )


@collect_tool()
def plotheatmap(
    *,
    matrix_file: str,
    heatmap_img: str,
    regions: Optional[str] = None,
    heatmap_matrix: Optional[str] = None,
     
) -> subprocess.CompletedProcess:
    """
    `deepTools plotHeatmap` creates a heatmap for scores associated with genomic regions.

    Args:
        matrix_file: Path to the gzipped matrix file generated by `deepTools computeMatrix` (.gz).
        heatmap_img: Output path for the plot image (.png, .eps, .pdf, or .svg). This is required.
        regions (optional): Output path for the BED file with sorted regions (.bed).
        heatmap_matrix (optional): Output path for the tab-separated matrix file (.tab).
  
    Returns:
        CompletedProcess instance containing information about the completed Snakemake process.
    """
    return run_plotheatmap(
        matrix_file=matrix_file,
        heatmap_img=heatmap_img,
        regions=regions,
        heatmap_matrix=heatmap_matrix,
         
    )
